apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lnadsdjx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-lnadsdjx:c2031bcd5288700eb7813ea4670618eafbfdd227@sha256:66b53350bede12c0ede5342fd36e71bcee5d0a3723fed47315c9ce72198ef7d5
          name: container-image
